export const PUBLIC_RPC_URLS: Record<number, string[]> = {
  1: [
    "https://eth-mainnet.public.blastapi.io",
    "https://eth.llamarpc.com",
  ],
  10: ["https://mainnet.optimism.io", "https://optimism.publicnode.com"],
  56: [
    "https://bsc-dataseed1.binance.org",
    "https://bsc-dataseed2.binance.org",
    "https://bsc-dataseed3.binance.org",
  ],
  100: ["wss://gnosis-rpc.publicnode.com"],
  130: [],

  137: [
    "https://polygon-rpc.com",
    "https://rpc.ankr.com/polygon",
    "https://polygon.public-rpc.com",
  ],
  146: [],
  324: ["https://mainnet.era.zksync.io", "https://zksync.meowrpc.com"],
  1101: [],
  1868: [],
  2741: [],
  5000: [],
  8453: ["https://base.llamarpc.com"],
  34443: [],
  42161: ["https://arb1.arbitrum.io/rpc", "https://arbitrum.public-rpc.com"],
  57073: [],
  57074: [],
  80094: [],
  81457: [],
  89999: [],
  534352: [],
};

export const MAINNET_CHAIN_IDS = {
  ETHEREUM: 1,
  BASE: 8453,
  ARBITRUM: 42161,
  ARBITRUM_NOVA: 42170,
  OPTIMISM: 10,
  POLYGON: 137,
  WORLDCHAIN: 480,
  UNICHAIN: 130,
  SONEIUM: 1868,
  POLYNOMIAL: 8008,
  OPBNB: 204,
  BERACHAIN: 80094,
} as const;

export const ALCHEMY_NETWORK_DETAILS: Record<number, string> = {
  [MAINNET_CHAIN_IDS.ETHEREUM]: "eth-mainnet",
  [MAINNET_CHAIN_IDS.BASE]: "base-mainnet",
  [MAINNET_CHAIN_IDS.ARBITRUM]: "arb-mainnet",
  [MAINNET_CHAIN_IDS.ARBITRUM_NOVA]: "arbnova-mainnet",
  [MAINNET_CHAIN_IDS.OPTIMISM]: "opt-mainnet",
  [MAINNET_CHAIN_IDS.POLYGON]: "polygon-mainnet",
  [MAINNET_CHAIN_IDS.WORLDCHAIN]: "worldchain-mainnet",
  [MAINNET_CHAIN_IDS.UNICHAIN]: "unichain-mainnet",
  [MAINNET_CHAIN_IDS.SONEIUM]: "soneium-mainnet",
  [MAINNET_CHAIN_IDS.POLYNOMIAL]: "polynomial-mainnet",
  [MAINNET_CHAIN_IDS.OPBNB]: "opbnb-mainnet",
  [MAINNET_CHAIN_IDS.BERACHAIN]: "berachain-mainnet",
};